FROM docker.io/alpine:3.21.3
RUN apk add --no-cache \
      openvpn \
      easy-rsa
COPY ip /sbin/ip
COPY controller-auth /usr/local/bin/controller-auth
COPY handle-connection /usr/local/bin/handle-connection
COPY handle-disconnection /usr/local/bin/handle-disconnection
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/openvpn", "/etc/openvpn/server.conf"]
