#!/bin/sh

source /etc/openvpn/config.env

# Add route to traefik
username=$common_name
cat <<EOF > /etc/openvpn/proxy/$username.yaml
http:
  # Add the router
  routers:
    router$username:
      entryPoints:
      - web
      middlewares:
      - m$username-stripprefix
      service: service-$username
      rule: PathPrefix(\`/$username\`)

  # Add the service
  services:
    service-$username:
      loadBalancer:
        servers:
        - url: https://$ifconfig_pool_remote_ip:9090/
        passHostHeader: true

  # Add middleware
  middlewares:
    m$username-stripprefix:
      stripPrefix:
        prefixes:
          - "/$username"
EOF

cat <<EOF > /etc/openvpn/proxy/${username}_direct_access.yaml
http:
  services:
    client-$username:
      loadBalancer:
        servers:
          - url: https://$ifconfig_pool_remote_ip:9090

  routers:
    to-client-$username:
      rule: PathPrefix(\`/tunnel/$username\`)
      service: client-$username
      entryPoints:
        - web
      middlewares:
        - strip-prefix-client-$username-middleware
        - compress-response

  middlewares:
    compress-response:
      compress: true

    strip-prefix-client-$username-middleware:
      stripPrefix:
        prefixes:
          - /tunnel/$username
EOF

echo -n "$ifconfig_pool_remote_ip" > /etc/openvpn/clients/$username
echo -n $(date +%s) > /etc/openvpn/status/$username.vpn