server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  # Syslog receiver configuration
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:6565
      listen_protocol: tcp
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
        instance: "promtail"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'
      - source_labels: ['__syslog_message_facility']
        target_label: 'facility'
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'

  # Additional syslog UDP receiver
  - job_name: syslog_udp
    syslog:
      listen_address: 0.0.0.0:6566
      listen_protocol: udp
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog_udp"
        instance: "promtail"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'
      - source_labels: ['__syslog_message_facility']
        target_label: 'facility'
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'
