FROM docker.io/alpine:3.22.5 AS build
RUN apk add --no-cache  \
    git \
    nodejs \
    npm
WORKDIR /build
# renovate: datasource=github-releases depName=NethServer/nethsecurity-ui
ARG UI_VERSION=855ca8db5deeb13dd3b7d50c8b30f2767420311b
RUN git clone --depth=1 --revision="$UI_VERSION" https://github.com/NethServer/nethsecurity-ui . \
    && npm ci \
    && VITE_UI_MODE=controller npm run build

FROM docker.io/alpine:3.22.5 AS dist
RUN apk add --no-cache lighttpd
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
COPY --from=build /build/dist /var/www/localhost/htdocs
