name: "Publish UI dist for nethsecurity (OpenWrt) build"

on:
  workflow_dispatch:
  push:
    paths:
      - 'ui/**'
    branches:
      - main
      - master

jobs:
  publish_images:
    name: 'Publish UI dist'
    runs-on: ubuntu-latest
    env:
      DO_SPACE_NAME: 'nethsecurity'
      DO_SPACE_REGION: 'ams3'
      CDN_NAME: 'updates.nethsecurity.nethserver.org'
    steps:
      - uses: actions/checkout@v3
      - id: build
        run: |
          # Build only the UI
          cd ui && bash build.sh
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_SPACE_ACCESS_KEY }}
          secret_key: ${{ secrets.DO_SPACE_SECRET_KEY }}
          space_name: ${{ env.DO_SPACE_NAME }}
          space_region: ${{ env.DO_SPACE_REGION }}
          cdn_domain: ${{ env.CDN_DOMAIN }}
          source: ui/ui.tar.gz
