name: Build

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  images:
    name: Images
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - name: nethsecurity-vpn
            directory: vpn
          - name: nethsecurity-api
            directory: api
          - name: nethsecurity-proxy
            directory: proxy
          - name: nethsecurity-ui
            directory: ui
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ${{ matrix.directory }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: dist
          cache-to: type=gha,mode=max
          cache-from: type=gha
          file: ${{ matrix.directory }}/Containerfile
          sbom: true
